// data.js — content extracted from existing portfolio
window.PORTFOLIO_DATA = {
  name: { first: 'Mamoun', last: 'Tavakol' },
  roles: ['Software Engineer', 'Software Engineer', 'Software Engineer', 'Designer'],
  location: 'Üsküdar, İstanbul',
  email: 'mamountkl@hotmail.com',
  phone: '(+90) 535 893 8977',
  about: {
    lead: "Computer Science graduate, fascinated by the quiet space between problems and the systems that solve them.",
    body: "Originally Syrian, raised in Saudi Arabia, settled in Istanbul. Seven years among minarets and bridges has tuned my ear to many languages — human and machine. I cook, I roam outdoors, I lose evenings to video games.",
    facts: [
      { label: 'Born', value: 'August 28, 1997' },
      { label: 'Based', value: 'Istanbul, Turkey' },
      { label: 'Roots', value: 'Syrian / Trilingual' },
      { label: 'Studied', value: 'Istanbul Şehir University' },
    ],
  },
  skills: [
    { name: 'Python', pct: 100 },
    { name: 'PostgreSQL & SQL', pct: 90 },
    { name: 'MongoDB', pct: 90 },
    { name: 'Node.js', pct: 85 },
    { name: 'HTML / CSS / JS', pct: 70 },
    { name: 'Go', pct: 60 },
    { name: 'C / C++', pct: 30 },
  ],
  experience: [
    {
      date: 'Jul 2021 — Present',
      role: 'Software Engineer',
      company: 'Syntonym',
      image: 'images/exp-syntonym.jpg',
      blurb: 'Build and maintain APIs across the cloud platform. Currently engineering data pipelines so customer signal can shape what we ship next.',
    },
    {
      date: 'Nov 2019 — Jun 2021',
      role: 'Python Developer',
      company: 'Boraq Group',
      image: 'images/exp-boraq.jpg',
      blurb: 'Wrote custom modules for clients on the Odoo ERP and shipped apps to the Odoo Store. Lived in Python, XML and JavaScript.',
    },
    {
      date: 'Jan 2020 — Oct 2021',
      role: 'Translator',
      company: 'Mülteciler Derneği',
      image: 'images/exp-translator.jpg',
      blurb: 'English ↔ Arabic translation, including projects for the World Health Organization and research with Prof. Ceren Acar Türk at Koç University.',
    },
    {
      date: 'Aug 2018 — Jan 2020',
      role: 'IT Engineer',
      company: 'Trauma Research Lab',
      image: 'images/exp-trauma.jpg',
      blurb: 'Kept field electronics and the Electronic Data Collector running smoothly for an active clinical lab.',
    },
    {
      date: 'Feb 2018 — Feb 2019',
      role: 'Teaching Assistant',
      company: 'Istanbul Şehir University',
      image: 'images/exp-teaching.jpg',
      blurb: 'Ran Python practice sessions, wrote project assignments, held office hours for undergraduate engineers.',
    },
    {
      date: 'Sep 2015 — Jan 2020',
      role: 'B.Sc. Computer Science & Engineering',
      company: 'Istanbul Şehir University',
      image: 'images/exp-education.jpg',
      blurb: 'Algorithms, data structures, computer architecture, networks, embedded systems, databases.',
    },
  ],
  work: [
    {
      title: 'Code Encryption',
      year: '2024',
      kind: 'OnPrem Application',
      tags: ['Python', 'PyArmor', 'Redis', 'SQLite'],
      image: 'images/work-encryption.jpg',
      body: "Encrypted Python source with <b>PyArmor</b> and built a licensing flow for our OnPrem product. Cached license state in <b>Redis</b> for low-latency checks and persisted to lightweight <b>SQLite</b> — small footprint, hard to crack.",
    },
    {
      title: 'Cloud Services',
      year: '2023',
      kind: 'Cloud Platform',
      tags: ['Node.js', 'Go', 'Python', 'MongoDB', 'Kafka'],
      image: 'images/work-cloud.jpg',
      body: "Backend cloud services for Syntonym — still early, so the stack is intentionally polyglot. <b>Node.js</b>, <b>Go</b> and <b>Python</b> services share a <b>MongoDB</b> core, with <b>Apache Kafka</b> as the event bus moving video and image jobs between workers.",
    },
    {
      title: 'NVIDIA AGX Xavier',
      year: '2023',
      kind: 'Edge Device',
      tags: ['MQTT', 'Redis', 'Edge'],
      image: 'images/work-edge.jpg',
      body: "Real-time edge pipeline on the Jetson AGX Xavier. <b>MQTT</b> moves metadata between the device and cloud while <b>Redis</b> caches frame metadata in-memory so the image stream never blocks.",
    },
    {
      title: 'Odoo Custom Modules',
      year: '2021',
      kind: 'ERP Extensions',
      tags: ['Python', 'XML', 'JavaScript'],
      image: 'images/work-odoo.jpg',
      body: "Across two years at Boraq Group I built custom modules and standalone apps for clients on the <b>Odoo</b> ERP platform — touching accounting, inventory and CRM workflows for SMBs in the region.",
    },
  ],
  logos: [
    { name: 'Syntonym', src: 'images/logos/syntonym-logo.png' },
    { name: 'Koç University', src: 'images/logos/Koç_University_logo.png' },
    { name: 'Boraq Group', src: 'images/logos/boraq-group.png' },
    { name: 'Trauma Research Lab', src: 'images/logos/trauma-lab.png' },
  ],
  services: [
    { title: 'Architecture Design', desc: 'Workflow and mechanism design — diagrams, databases, edge case detection — for the solution you have in mind.' },
    { title: 'Web Development', desc: 'Full-stack web app from scratch: design, backend, frontend implementation.' },
    { title: 'UI / UX Design', desc: 'Product design in Figma or Adobe XD, oriented around clarity and the lightest possible interaction.' },
    { title: 'Graphics Design', desc: 'Simple, considered graphics for blogs, journal articles, and product surfaces.' },
    { title: 'Consultancy', desc: 'Audit existing flows, surface design errors, propose business-aligned solutions for you and your customers.' },
    { title: 'Translation', desc: 'English ↔ Arabic for documents, scripts and articles. Audio and video transcription on request.' },
  ],
};
